version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: riwaaya_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=riwaaya_db
      - POSTGRES_USER=riwaaya_user
      - POSTGRES_PASSWORD=riwaaya_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: riwaaya_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: riwaaya_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://riwaaya_user:riwaaya_pass@db:5432/riwaaya_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: riwaaya_celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://riwaaya_user:riwaaya_pass@db:5432/riwaaya_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    container_name: riwaaya_celery_beat
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://riwaaya_user:riwaaya_pass@db:5432/riwaaya_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
