# Generated by Django 5.1.15 on 2026-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='color_hex',
            field=models.CharField(blank=True, default='#B8963E', max_length=30),
        ),
    ]
