# Generated by Django 5.1.15 on 2026-09-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_variant_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='readymade', max_length=30),
        ),
    ]
