from django.urls import path

from apps.node_compat.views import (
    AddressListView, AddressDetailView, AdminOrdersView, AdminProductApprovalView,
    AdminSellerApprovalView, AdminSellersView, AdminStatsView, AdminSeedView,
    AuthLoginView, AuthMeView, AuthRegisterView, AuthSellerRegisterView,
    AuthSendOtpView, AuthVerifyOtpView, CartItemView, CartMergeView, CartView,
    HealthView, OrderDetailView, OrderListCreateView, PaymentCreateOrderView,
    PaymentVerifyView, ProductDetailView, ProductListCreateView,
    ProductUploadView, ProductVariantView, SellerOrderStatusView,
    SellerOrdersView, SellerProductDetailView, SellerProductsView,
    SellerStatsView, WishlistView, WishlistSyncView, WishlistToggleView,
)

urlpatterns = [
    path('auth/register', AuthRegisterView.as_view()),
    path('auth/register/customer', AuthRegisterView.as_view()),
    path('auth/register/seller', AuthSellerRegisterView.as_view()),
    path('auth/login', AuthLoginView.as_view()),
    path('auth/me', AuthMeView.as_view()),
    path('auth/send-otp', AuthSendOtpView.as_view()),
    path('auth/verify-otp', AuthVerifyOtpView.as_view()),
    path('products', ProductListCreateView.as_view()),
    path('products/', ProductListCreateView.as_view()),
    path('products/upload', ProductUploadView.as_view()),
    path('products/<uuid:product_id>', ProductDetailView.as_view()),
    path('products/<uuid:product_id>/variants', ProductVariantView.as_view()),
    path('seller/stats', SellerStatsView.as_view()),
    path('seller/products', SellerProductsView.as_view()),
    path('seller/products/<uuid:product_id>', SellerProductDetailView.as_view()),
    path('seller/orders', SellerOrdersView.as_view()),
    path('seller/orders/<uuid:order_id>/status', SellerOrderStatusView.as_view()),
    path('seller/orders/<uuid:order_id>', SellerOrderStatusView.as_view()),
    path('admin/stats', AdminStatsView.as_view()),
    path('admin/sellers', AdminSellersView.as_view()),
    path('admin/sellers/<uuid:seller_id>/approve', AdminSellerApprovalView.as_view()),
    path('admin/products/<uuid:product_id>/approve', AdminProductApprovalView.as_view()),
    path('admin/orders', AdminOrdersView.as_view()),
    path('admin/seed', AdminSeedView.as_view()),
    path('orders', OrderListCreateView.as_view()),
    path('orders/myorders', OrderListCreateView.as_view()),
    path('orders/<uuid:order_id>', OrderDetailView.as_view()),
    path('cart', CartView.as_view()),
    path('cart/', CartView.as_view()),
    path('cart/merge', CartMergeView.as_view()),
    path('cart/<str:item_id>', CartItemView.as_view()),
    path('payment/create-order', PaymentCreateOrderView.as_view()),
    path('payment/verify', PaymentVerifyView.as_view()),
    path('wishlist', WishlistView.as_view()),
    path('wishlist/toggle', WishlistToggleView.as_view()),
    path('wishlist/sync', WishlistSyncView.as_view()),
    path('addresses', AddressListView.as_view()),
    path('addresses/', AddressListView.as_view()),
    path('addresses/<uuid:address_id>', AddressDetailView.as_view()),
    path('addresses/<uuid:address_id>/default', AddressDetailView.as_view()),
]